Create an array containing the values 1–15 and reshaping it into a 3-by-5 array.

In [1]:
import numpy as np

array_2D = np.arange(1, 16).reshape(3, 5)

#another method
#array_1D = np.arange(1, 16)
#array_2D = np.array([array_1D[i:i+5] for i in range (0, 15, 5)])

print(array_2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Select row 2

In [3]:
print("row: ",array_2D[2])

row:  [11 12 13 14 15]


Select column 4

In [5]:
print("column: ",array_2D[:,4])

column:  [ 5 10 15]


Select rows 0 and 1

In [7]:
print("Two rows:\n",array_2D[0:2,:])

Two rows:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Select columns 2–4

In [9]:
print("Three columns:\n",array_2D[:,2:5].T)

Three columns:
 [[ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


Select the element that is in row 1 and column 4

In [25]:
print("Element: ",array_2D[1,4])

Element:  10


Select all elements from rows 1 and 2 that are in columns 0, 2 and 4

In [13]:
print("Elements:\n",array_2D[1:3,[0,2,4]])

Elements:
 [[ 6  8 10]
 [11 13 15]]


Using pandas, create a Series from the list [5, 11, 13, 15]

In [31]:
import pandas as pd

series = pd.Series([5, 11, 13, 15])

print(series)

0     5
1    11
2    13
3    15
dtype: int64


Create a Series with five elements that are all 110.0

In [34]:
series = pd.Series([110.0] * 5)

print(series)

0    110.0
1    110.0
2    110.0
3    110.0
4    110.0
dtype: float64


Create a Series with 20 elements that are all random numbers in the range 0 to 200. Use method describe to produce the Series’ basic descriptive statistics.

In [71]:
random_series = pd.Series(np.random.randint(0, 201, size=20))

print("Random Series:\n", random_series)

print("Statistics:\n",random_series.describe())

Random Series: 
 0      54
1      50
2      23
3     141
4     105
5      35
6       9
7     127
8      71
9      88
10     91
11    103
12    158
13     33
14      0
15    102
16    115
17     89
18    166
19     91
dtype: int32
Statistics: 
 count     20.000000
mean      82.550000
std       47.633994
min        0.000000
25%       46.250000
50%       90.000000
75%      107.500000
max      166.000000
dtype: float64


Create a Series called temperatures of the floating-point values 99.6, 99.9, 100.2 and 97.9. Using the index keyword argument, specify the custom indices 'Julie', 'Charlie', 'Sam' and 'Andrea'

In [42]:
temperatures = pd.Series([99.6, 99.9, 100.2, 97.9], index=['Julie', 'Charlie', 'Sam','Andrea'])

print(temperatures)

Julie       99.6
Charlie     99.9
Sam        100.2
Andrea      97.9
dtype: float64


Form a dictionary from the names and values in previous part, then use it to initialize a Series

temperatures_dictionary = {'Julie': 99.6,'Charlie': 99.9,'Sam': 100.2,'Andrea': 97.9}

print(temperatures_dictionary)

Create a DataFrame named temperatures from a dictionary of three temperature readings each for 'Maxine', 'James' and 'Amanda'.

In [48]:
temperatures_dict = {'Maxine': [98.6, 99.1, 98.7],'James': [100.2, 99.8, 101.0],'Amanda': [97.5, 98.0, 98.3]}

temperatures_dataframe = pd.DataFrame(temperatures_dict)

print(temperatures_dataframe)

   Maxine  James  Amanda
0    98.6  100.2    97.5
1    99.1   99.8    98.0
2    98.7  101.0    98.3


Recreate the DataFrame temperatures in Part (a) with custom indices using the index keyword argument and a list containing 'Morning', 'Afternoon' and 'Evening'.

In [53]:
temperatures_index = pd.DataFrame(temperatures_dict, index=['Morning','Afternoon','Evening'])

print(temperatures_index)

           Maxine  James  Amanda
Morning      98.6  100.2    97.5
Afternoon    99.1   99.8    98.0
Evening      98.7  101.0    98.3


Select from temperatures the column of temperature readings for 'Maxine'

In [56]:
print(temperatures_index['Maxine'])

Morning      98.6
Afternoon    99.1
Evening      98.7
Name: Maxine, dtype: float64


Select from temperatures the row of 'Morning' temperature readings

In [63]:
print(temperatures_index.loc['Morning'])

Maxine     98.6
James     100.2
Amanda     97.5
Name: Morning, dtype: float64


Select from temperatures the rows for 'Morning' and 'Evening' temperature readings.

In [66]:
print(temperatures_index.loc[['Morning', 'Evening']])

         Maxine  James  Amanda
Morning    98.6  100.2    97.5
Evening    98.7  101.0    98.3


Select from temperatures the columns of temperature readings for 'Amanda' and 'Maxine'

In [69]:
print(temperatures_index[['Amanda', 'Maxine']])

           Amanda  Maxine
Morning      97.5    98.6
Afternoon    98.0    99.1
Evening      98.3    98.7


Select from temperatures the elements for 'Amanda' and 'Maxine' in the 'Morning' and 'Afternoon'.

In [74]:
print(temperatures_index.loc[['Morning', 'Afternoon'], ['Amanda', 'Maxine']])

           Amanda  Maxine
Morning      97.5    98.6
Afternoon    98.0    99.1


Use the describe method to produce temperatures’ descriptive statistics.

In [77]:
print(temperatures_index.describe())

          Maxine       James     Amanda
count   3.000000    3.000000   3.000000
mean   98.800000  100.333333  97.933333
std     0.264575    0.611010   0.404145
min    98.600000   99.800000  97.500000
25%    98.650000  100.000000  97.750000
50%    98.700000  100.200000  98.000000
75%    98.900000  100.600000  98.150000
max    99.100000  101.000000  98.300000


Transpose temperatures.

In [80]:
print(temperatures_index.T)

        Morning  Afternoon  Evening
Maxine     98.6       99.1     98.7
James     100.2       99.8    101.0
Amanda     97.5       98.0     98.3


Sort temperatures so that its column names are in alphabetical order.

In [83]:
print(temperatures_index.sort_index(axis=1))

           Amanda  James  Maxine
Morning      97.5  100.2    98.6
Afternoon    98.0   99.8    99.1
Evening      98.3  101.0    98.7
